/**
 * Generated Permission Types
 *
 * Auto-generated from shared/permissions.yaml
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated: 2026-01-31T16:47:53.867669
 */

// Actions that can be performed on resources
export const Actions = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  MANAGE: 'manage',
  MODERATE: 'moderate',
  EXPORT: 'export',
  INVITE: 'invite',
  GRADE: 'grade',
  SUBMIT: 'submit',
  ENROLL: 'enroll',
} as const;

export type Action = (typeof Actions)[keyof typeof Actions];

// Types of resources in the system
export const ResourceTypes = {
  ORGANIZATION: 'organization',
  COURSE: 'course',
  CHAPTER: 'chapter',
  ACTIVITY: 'activity',
  ASSIGNMENT: 'assignment',
  QUIZ: 'quiz',
  USER: 'user',
  USERGROUP: 'usergroup',
  COLLECTION: 'collection',
  ROLE: 'role',
  CERTIFICATE: 'certificate',
  DISCUSSION: 'discussion',
  FILE: 'file',
  ANALYTICS: 'analytics',
  TRAIL: 'trail',
  EXAM: 'exam',
  PAYMENT: 'payment',
  API_TOKEN: 'api_token',
} as const;

export type ResourceType = (typeof ResourceTypes)[keyof typeof ResourceTypes];

// Scopes define the extent of a permission
export const Scopes = {
  ALL: 'all',
  OWN: 'own',
  ASSIGNED: 'assigned',
  ORG: 'org',
} as const;

export type Scope = (typeof Scopes)[keyof typeof Scopes];

// Role slugs
export const RoleSlugs = {
  SUPER_ADMIN: 'super-admin',
  ORG_ADMIN: 'org-admin',
  MAINTAINER: 'maintainer',
  INSTRUCTOR: 'instructor',
  MODERATOR: 'moderator',
  USER: 'user',
} as const;

export type RoleSlug = (typeof RoleSlugs)[keyof typeof RoleSlugs];

/**
 * Build a permission name from components.
 * Format: {resource}:{action}:{scope}
 * Example: course:update:own
 */
export function buildPermissionName(
  resource: ResourceType,
  action: Action,
  scope: Scope = Scopes.ALL,
): string {
  return `${resource}:${action}:${scope}`;
}

/**
 * Parse a permission name into components.
 */
export function parsePermissionName(name: string): {
  resource: ResourceType;
  action: Action;
  scope: Scope;
} | null {
  const parts = name.split(':');
  if (parts.length !== 3) {
    return null;
  }
  return {
    resource: parts[0] as ResourceType,
    action: parts[1] as Action,
    scope: parts[2] as Scope,
  };
}

/**
 * Check if a role slug is an admin role.
 */
export function isAdminRole(roleSlug: string): boolean {
  return (
    roleSlug === RoleSlugs.SUPER_ADMIN ||
    roleSlug === RoleSlugs.ORG_ADMIN
  );
}

/**
 * Check if a role slug is instructor or higher.
 */
export function isInstructorOrHigher(roleSlug: string): boolean {
  return (
    roleSlug === RoleSlugs.SUPER_ADMIN ||
    roleSlug === RoleSlugs.ORG_ADMIN ||
    roleSlug === RoleSlugs.MAINTAINER ||
    roleSlug === RoleSlugs.INSTRUCTOR
  );
}

/**
 * Permission name type for better type safety.
 */
export type PermissionName = `${ResourceType}:${Action}:${Scope}`;

/**
 * Permission check result.
 */
export interface PermissionCheck {
  action: Action;
  resource: ResourceType;
  scope?: Scope;
}
