services:
  app:
    build: .
    ports:
      - '80:80'
    volumes:
      - .:/usr/openu
    env_file:
      - ./extra/example-openu-conf.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres:17.5-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=openu
      - POSTGRES_PASSWORD=openu
      - POSTGRES_DB=openu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openu"]
      interval: 5s
      timeout: 4s
      retries: 5
  redis:
    image: redis:8.0.2-alpine
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 4s
      retries: 5
  chromadb:
    image: chromadb/chroma:latest
    restart: always
    ports:
      - '8000:8000'

volumes:
  postgres_data:
