"""
Generated Role Permission Mappings

Auto-generated from shared/permissions.yaml
DO NOT EDIT THIS FILE MANUALLY
Generated: 2026-01-31T16:47:53.868332
"""

from src.db.permissions.generated_enums import Action, ResourceType, Scope

# Role slug constants
class RoleSlug:
    """Standard role slugs used across the platform."""

    SUPER_ADMIN = "super-admin"
    ORG_ADMIN = "org-admin"
    MAINTAINER = "maintainer"
    INSTRUCTOR = "instructor"
    MODERATOR = "moderator"
    USER = "user"


# Role permission mappings
ROLE_PERMISSIONS: dict[str, list[str]] = {
    "super-admin": [
        "*:*:*",
    ],
    "org-admin": [
        "organization:manage:own",
        "organization:update:own",
        "organization:read:own",
        "course:*:org",
        "chapter:*:org",
        "activity:*:org",
        "assignment:*:org",
        "quiz:*:org",
        "exam:*:org",
        "user:invite:org",
        "user:read:org",
        "user:update:org",
        "usergroup:*:org",
        "collection:*:org",
        "role:read:org",
        "role:create:org",
        "role:update:org",
        "certificate:*:org",
        "discussion:moderate:org",
        "analytics:read:org",
        "payment:manage:org",
    ],
    "maintainer": [
        "course:create:org",
        "course:read:all",
        "course:update:org",
        "course:delete:own",
        "course:manage:own",
        "chapter:*:org",
        "activity:*:org",
        "assignment:*:org",
        "quiz:*:org",
        "exam:*:org",
        "collection:create:org",
        "collection:read:all",
        "collection:update:own",
        "collection:delete:own",
        "discussion:moderate:org",
        "analytics:read:own",
        "certificate:create:own",
    ],
    "instructor": [
        "course:create:org",
        "course:read:all",
        "course:update:own",
        "course:delete:own",
        "chapter:create:own",
        "chapter:read:all",
        "chapter:update:own",
        "chapter:delete:own",
        "activity:create:own",
        "activity:read:all",
        "activity:update:own",
        "activity:delete:own",
        "assignment:*:own",
        "quiz:*:own",
        "exam:*:own",
        "collection:create:org",
        "collection:read:all",
        "collection:update:own",
        "discussion:moderate:own",
        "analytics:read:own",
        "user:read:assigned",
    ],
    "moderator": [
        "course:read:all",
        "discussion:moderate:org",
        "discussion:read:all",
        "discussion:update:org",
        "discussion:delete:org",
        "user:read:org",
    ],
    "user": [
        "course:read:all",
        "course:enroll:all",
        "chapter:read:all",
        "activity:read:all",
        "assignment:submit:assigned",
        "assignment:read:assigned",
        "quiz:submit:assigned",
        "quiz:read:assigned",
        "exam:submit:assigned",
        "exam:read:assigned",
        "collection:read:all",
        "discussion:create:org",
        "discussion:read:all",
        "discussion:update:own",
        "discussion:delete:own",
        "user:read:own",
        "user:update:own",
        "certificate:read:own",
    ],
}

# Role groups for common permission checks
ADMIN_ROLE_SLUGS = frozenset({
    RoleSlug.SUPER_ADMIN,
    RoleSlug.ORG_ADMIN,
})

ADMIN_OR_MAINTAINER_SLUGS = frozenset({
    RoleSlug.SUPER_ADMIN,
    RoleSlug.ORG_ADMIN,
    RoleSlug.MAINTAINER,
})

INSTRUCTOR_OR_HIGHER_SLUGS = frozenset({
    RoleSlug.SUPER_ADMIN,
    RoleSlug.ORG_ADMIN,
    RoleSlug.MAINTAINER,
    RoleSlug.INSTRUCTOR,
})

CONTENT_CREATOR_SLUGS = frozenset({
    RoleSlug.SUPER_ADMIN,
    RoleSlug.ORG_ADMIN,
    RoleSlug.MAINTAINER,
    RoleSlug.INSTRUCTOR,
})


def is_admin_role(role_slug: str) -> bool:
    """Check if the role slug is an admin role."""
    return role_slug in ADMIN_ROLE_SLUGS


def is_admin_or_maintainer_role(role_slug: str) -> bool:
    """Check if the role slug is admin or maintainer."""
    return role_slug in ADMIN_OR_MAINTAINER_SLUGS


def is_instructor_or_higher_role(role_slug: str) -> bool:
    """Check if the role slug is instructor or higher privilege."""
    return role_slug in INSTRUCTOR_OR_HIGHER_SLUGS


def is_content_creator_role(role_slug: str) -> bool:
    """Check if the role slug can create content."""
    return role_slug in CONTENT_CREATOR_SLUGS
