"""
Generated Permission Enums

Auto-generated from shared/permissions.yaml
DO NOT EDIT THIS FILE MANUALLY
Generated: 2026-01-31T16:47:53.866259
"""

from enum import Enum


class Action(str, Enum):
    """Actions that can be performed on resources."""

    CREATE = "create"
    READ = "read"
    UPDATE = "update"
    DELETE = "delete"
    MANAGE = "manage"
    MODERATE = "moderate"
    EXPORT = "export"
    INVITE = "invite"
    GRADE = "grade"
    SUBMIT = "submit"
    ENROLL = "enroll"


class ResourceType(str, Enum):
    """Types of resources in the system."""
    
    ORGANIZATION = "organization"
    COURSE = "course"
    CHAPTER = "chapter"
    ACTIVITY = "activity"
    ASSIGNMENT = "assignment"
    QUIZ = "quiz"
    USER = "user"
    USERGROUP = "usergroup"
    COLLECTION = "collection"
    ROLE = "role"
    CERTIFICATE = "certificate"
    DISCUSSION = "discussion"
    FILE = "file"
    ANALYTICS = "analytics"
    TRAIL = "trail"
    EXAM = "exam"
    PAYMENT = "payment"
    API_TOKEN = "api_token"


class Scope(str, Enum):
    """Scope of a permission - determines what resources it applies to."""
    
    ALL = "all"
    OWN = "own"
    ASSIGNED = "assigned"
    ORG = "org"


def build_permission_name(
    resource: ResourceType,
    action: Action,
    scope: Scope = Scope.ALL,
) -> str:
    """Build a permission name from components."""
    return f"{resource.value}:{action.value}:{scope.value}"


def parse_permission_name(name: str) -> tuple[str, str, str]:
    """Parse a permission name into components."""
    parts = name.split(":")
    if len(parts) != 3:
        raise ValueError(f"Invalid permission name: {name}")
    return parts[0], parts[1], parts[2]
