"""
Generated Permission Enums

Auto-generated from shared/permissions.yaml
DO NOT EDIT THIS FILE MANUALLY
Generated: 2026-01-31T20:44:53.193668
"""

from enum import Enum, StrEnum


class Action(StrEnum):
    """Actions that can be performed on resources."""

    CREATE = "CREATE"
    READ = "READ"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    MANAGE = "MANAGE"
    MODERATE = "MODERATE"
    EXPORT = "EXPORT"
    INVITE = "INVITE"
    GRADE = "GRADE"
    SUBMIT = "SUBMIT"
    ENROLL = "ENROLL"
    ACCESS = "ACCESS"  # For API access checks


class ResourceType(StrEnum):
    """Types of resources in the system."""

    ORGANIZATION = "ORGANIZATION"
    COURSE = "COURSE"
    CHAPTER = "CHAPTER"
    ACTIVITY = "ACTIVITY"
    ASSIGNMENT = "ASSIGNMENT"
    QUIZ = "QUIZ"
    USER = "USER"
    USERGROUP = "USERGROUP"
    COLLECTION = "COLLECTION"
    ROLE = "ROLE"
    CERTIFICATE = "CERTIFICATE"
    DISCUSSION = "DISCUSSION"
    FILE = "FILE"
    ANALYTICS = "ANALYTICS"
    TRAIL = "TRAIL"
    EXAM = "EXAM"
    PAYMENT = "PAYMENT"
    API_TOKEN = "API_TOKEN"
    API = "API"  # For API access checks


class Scope(StrEnum):
    """Scope of a permission - determines what resources it applies to."""

    ALL = "ALL"
    OWN = "OWN"
    ASSIGNED = "ASSIGNED"
    ORG = "ORG"


def build_permission_name(
    resource: ResourceType,
    action: Action,
    scope: Scope = Scope.ALL,
) -> str:
    """Build a permission name from components."""
    return f"{resource.value.lower()}:{action.value.lower()}:{scope.value.lower()}"


def parse_permission_name(name: str) -> tuple[str, str, str]:
    """Parse a permission name into components."""
    parts = name.split(":")
    if len(parts) != 3:
        msg = f"Invalid permission name: {name}"
        raise ValueError(msg)
    return parts[0], parts[1], parts[2]
