"""empty message

Revision ID: 01298eb34544
Revises: a7aca90f424a
Create Date: 2026-04-05 13:51:13.902344

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01298eb34544"
down_revision: Union[str, None] = "a7aca90f424a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("index_submissions_on_token"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(
        op.f("document_chunks_collection_name_idx"), table_name="document_chunks"
    )
    op.drop_index(
        op.f("document_chunks_embedding_hnsw_idx"),
        table_name="document_chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_index(op.f("document_chunks_inserted_at_idx"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_table("clients")
    op.drop_table("auth_audit_log")
    op.drop_table("languages")
    op.drop_table("schema_migrations")
    op.drop_table("chapteractivity")
    op.drop_table("coursechapter")
    op.drop_table("ar_internal_metadata")
    op.drop_index(op.f("ix_auth_sessions_refresh_hash"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_session_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("idx_activity_activity_uuid"), table_name="activity")
    op.drop_constraint(op.f("uq_activity_activity_uuid"), "activity", type_="unique")
    op.drop_index(op.f("ix_analytics_event_course_date"), table_name="analytics_event")
    op.drop_index(op.f("ix_analytics_event_type_date"), table_name="analytics_event")
    op.drop_index(op.f("ix_analytics_event_user_date"), table_name="analytics_event")
    op.alter_column(
        "assignment",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "assignment",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_assignment_assignment_uuid"), table_name="assignment")
    op.drop_constraint(
        op.f("uq_assignment_assignment_uuid"), "assignment", type_="unique"
    )
    op.alter_column(
        "assignmenttask",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignmenttask",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("idx_assignmenttask_assignment_task_uuid"), table_name="assignmenttask"
    )
    op.drop_constraint(
        op.f("uq_assignmenttask_assignment_task_uuid"), "assignmenttask", type_="unique"
    )
    op.alter_column(
        "assignmenttasksubmission",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignmenttasksubmission",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("idx_assignmenttasksubmission_assignment_task_submission_uuid"),
        table_name="assignmenttasksubmission",
    )
    op.drop_constraint(
        op.f("uq_assignmenttasksubmission_assignment_task_submission_uuid"),
        "assignmenttasksubmission",
        type_="unique",
    )
    op.alter_column(
        "assignmentusersubmission",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignmentusersubmission",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignmentusersubmission",
        "submitted_at",
        existing_type=sa.TEXT(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="submitted_at::timestamp with time zone",
        existing_nullable=True,
    )
    op.alter_column(
        "assignmentusersubmission",
        "graded_at",
        existing_type=sa.TEXT(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="graded_at::timestamp with time zone",
        existing_nullable=True,
    )
    op.drop_index(
        op.f("idx_assignmentusersubmission_assignmentusersubmission_uuid"),
        table_name="assignmentusersubmission",
    )
    op.drop_constraint(
        op.f("uq_assignmentusersubmission_assignmentusersubmission_uuid"),
        "assignmentusersubmission",
        type_="unique",
    )
    op.alter_column(
        "block",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "block",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_block_block_uuid"), table_name="block")
    op.drop_constraint(op.f("uq_block_block_uuid"), "block", type_="unique")
    op.drop_index(
        op.f("idx_certificateuser_user_certification_uuid"),
        table_name="certificateuser",
    )
    op.drop_constraint(
        op.f("uq_certificateuser_user_certification_uuid"),
        "certificateuser",
        type_="unique",
    )
    op.alter_column(
        "certifications",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "certifications",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_index(
        op.f("idx_certifications_certification_uuid"), table_name="certifications"
    )
    op.alter_column(
        "chapter",
        "creation_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chapter",
        "update_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_chapter_chapter_uuid"), table_name="chapter")
    op.drop_constraint(op.f("uq_chapter_chapter_uuid"), "chapter", type_="unique")
    op.alter_column(
        "collection",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "collection",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_collection_collection_uuid"), table_name="collection")
    op.drop_constraint(
        op.f("uq_collection_collection_uuid"), "collection", type_="unique"
    )
    op.alter_column(
        "collectioncourse",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "collectioncourse",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_course_course_uuid"), table_name="course")
    op.drop_constraint(op.f("uq_course_course_uuid"), "course", type_="unique")
    op.alter_column(
        "coursediscussion",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "coursediscussion",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "courseupdate",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "courseupdate",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_courseupdate_courseupdate_uuid"), table_name="courseupdate")
    op.drop_constraint(
        op.f("uq_courseupdate_courseupdate_uuid"), "courseupdate", type_="unique"
    )
    op.alter_column(
        "discussiondislike",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "discussionlike",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "exam",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "exam",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "examattempt",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "examattempt",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("uq_permissions_name"), "permissions", type_="unique")
    op.alter_column(
        "question",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "question",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_attempt",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_attempt",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_question_stat",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_question_stat",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "resourceauthor",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "resourceauthor",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "role_permissions",
        "granted_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_submission_activity_status"), table_name="submission")
    op.drop_index(
        op.f("ix_submission_one_draft_per_user_activity"),
        table_name="submission",
        postgresql_where="((status)::text = 'DRAFT'::text)",
    )
    op.alter_column(
        "trail",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "trail",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "trailrun",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "trailrun",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "trailstep",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "trailstep",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "assigned_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "usergroup",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "usergroup",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_usergroup_usergroup_uuid"), table_name="usergroup")
    op.drop_constraint(op.f("uq_usergroup_usergroup_uuid"), "usergroup", type_="unique")
    op.alter_column(
        "usergroupresource",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "usergroupresource",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "usergroupuser",
        "creation_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    op.alter_column(
        "usergroupuser",
        "update_date",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "usergroupuser",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "usergroupuser",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "usergroupresource",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "usergroupresource",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_usergroup_usergroup_uuid"),
        "usergroup",
        ["usergroup_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_usergroup_usergroup_uuid"),
        "usergroup",
        ["usergroup_uuid"],
        unique=False,
    )
    op.alter_column(
        "usergroup",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "usergroup",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_roles",
        "assigned_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "trailstep",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "trailstep",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "trailrun",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "trailrun",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "trail",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "trail",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_submission_one_draft_per_user_activity"),
        "submission",
        ["user_id", "activity_id"],
        unique=True,
        postgresql_where="((status)::text = 'DRAFT'::text)",
    )
    op.create_index(
        op.f("ix_submission_activity_status"),
        "submission",
        ["activity_id", "status"],
        unique=False,
    )
    op.alter_column(
        "role_permissions",
        "granted_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "resourceauthor",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "resourceauthor",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_question_stat",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_question_stat",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_attempt",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "quiz_attempt",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "question",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "question",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_permissions_name"),
        "permissions",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "examattempt",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "examattempt",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "exam",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "exam",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "discussionlike",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "discussiondislike",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_courseupdate_courseupdate_uuid"),
        "courseupdate",
        ["courseupdate_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_courseupdate_courseupdate_uuid"),
        "courseupdate",
        ["courseupdate_uuid"],
        unique=False,
    )
    op.alter_column(
        "courseupdate",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "courseupdate",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "coursediscussion",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "coursediscussion",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_course_course_uuid"),
        "course",
        ["course_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_course_course_uuid"), "course", ["course_uuid"], unique=False
    )
    op.alter_column(
        "collectioncourse",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "collectioncourse",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_collection_collection_uuid"),
        "collection",
        ["collection_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_collection_collection_uuid"),
        "collection",
        ["collection_uuid"],
        unique=False,
    )
    op.alter_column(
        "collection",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "collection",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_chapter_chapter_uuid"),
        "chapter",
        ["chapter_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_chapter_chapter_uuid"), "chapter", ["chapter_uuid"], unique=False
    )
    op.alter_column(
        "chapter",
        "update_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "chapter",
        "creation_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("idx_certifications_certification_uuid"),
        "certifications",
        ["certification_uuid"],
        unique=False,
    )
    op.alter_column(
        "certifications",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "certifications",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_certificateuser_user_certification_uuid"),
        "certificateuser",
        ["user_certification_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_certificateuser_user_certification_uuid"),
        "certificateuser",
        ["user_certification_uuid"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_block_block_uuid"),
        "block",
        ["block_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_block_block_uuid"), "block", ["block_uuid"], unique=False)
    op.alter_column(
        "block",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "block",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_assignmentusersubmission_assignmentusersubmission_uuid"),
        "assignmentusersubmission",
        ["assignmentusersubmission_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_assignmentusersubmission_assignmentusersubmission_uuid"),
        "assignmentusersubmission",
        ["assignmentusersubmission_uuid"],
        unique=False,
    )
    op.alter_column(
        "assignmentusersubmission",
        "graded_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TEXT(),
        postgresql_using="graded_at::text",
        existing_nullable=True,
    )
    op.alter_column(
        "assignmentusersubmission",
        "submitted_at",
        existing_type=sa.DateTime(timezone=True),
        type_=sa.TEXT(),
        postgresql_using="submitted_at::text",
        existing_nullable=True,
    )
    op.alter_column(
        "assignmentusersubmission",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignmentusersubmission",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_assignmenttasksubmission_assignment_task_submission_uuid"),
        "assignmenttasksubmission",
        ["assignment_task_submission_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_assignmenttasksubmission_assignment_task_submission_uuid"),
        "assignmenttasksubmission",
        ["assignment_task_submission_uuid"],
        unique=False,
    )
    op.alter_column(
        "assignmenttasksubmission",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignmenttasksubmission",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_assignmenttask_assignment_task_uuid"),
        "assignmenttask",
        ["assignment_task_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_assignmenttask_assignment_task_uuid"),
        "assignmenttask",
        ["assignment_task_uuid"],
        unique=False,
    )
    op.alter_column(
        "assignmenttask",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "assignmenttask",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_assignment_assignment_uuid"),
        "assignment",
        ["assignment_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_assignment_assignment_uuid"),
        "assignment",
        ["assignment_uuid"],
        unique=False,
    )
    op.alter_column(
        "assignment",
        "update_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "assignment",
        "creation_date",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_analytics_event_user_date"),
        "analytics_event",
        ["user_id", "event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_event_type_date"),
        "analytics_event",
        ["event_type", "event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_event_course_date"),
        "analytics_event",
        ["course_id", "event_date"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("uq_activity_activity_uuid"),
        "activity",
        ["activity_uuid"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_activity_activity_uuid"), "activity", ["activity_uuid"], unique=False
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("refresh_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("prev_hash", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("device_ua", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("device_ip", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "last_used_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "revoked_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("revoke_reason", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("auth_sessions_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("auth_sessions_pkey")),
    )
    op.create_index(
        op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_auth_sessions_session_id"),
        "auth_sessions",
        ["session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_auth_sessions_refresh_hash"),
        "auth_sessions",
        ["refresh_hash"],
        unique=False,
    )
    op.create_table(
        "ar_internal_metadata",
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("ar_internal_metadata_pkey")),
    )
    op.create_table(
        "coursechapter",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("course_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("chapter_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("creation_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("update_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapter.id"],
            name=op.f("coursechapter_chapter_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("coursechapter_course_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("coursechapter_pkey")),
    )
    op.create_table(
        "chapteractivity",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("chapter_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("activity_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("course_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("creation_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("update_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activity.id"],
            name=op.f("chapteractivity_activity_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapter.id"],
            name=op.f("chapteractivity_chapter_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
            name=op.f("chapteractivity_course_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chapteractivity_pkey")),
    )
    op.create_table(
        "schema_migrations",
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("schema_migrations_pkey")),
    )
    op.create_table(
        "languages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("compile_cmd", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("run_cmd", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source_file", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "is_archived",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("languages_pkey")),
    )
    op.create_table(
        "auth_audit_log",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("session_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("event", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ip", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_agent", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "event_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("auth_audit_log_pkey")),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("clients_pkey")),
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("collection_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("document", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "inserted_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_chunks_pkey")),
    )
    op.create_index(
        op.f("document_chunks_inserted_at_idx"),
        "document_chunks",
        ["inserted_at"],
        unique=False,
    )
    op.create_index(
        op.f("document_chunks_embedding_hnsw_idx"),
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("document_chunks_collection_name_idx"),
        "document_chunks",
        ["collection_name"],
        unique=False,
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("language_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stdin", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("expected_output", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("stdout", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "finished_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("memory", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stderr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("number_of_runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cpu_time_limit", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("cpu_extra_time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("wall_time_limit", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("memory_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stack_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "max_processes_and_or_threads",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "enable_per_process_and_thread_time_limit",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "enable_per_process_and_thread_memory_limit",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("max_file_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("compile_output", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("exit_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("exit_signal", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("wall_time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("compiler_options", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "command_line_arguments", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "redirect_stderr_to_stdout",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("callback_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "additional_files", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        sa.Column("enable_network", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("submissions_pkey")),
    )
    op.create_index(
        op.f("index_submissions_on_token"), "submissions", ["token"], unique=False
    )
    # ### end Alembic commands ###
