"""mark discarded autogenerated diff as no-op

Revision ID: 01298eb34544
Revises: a7aca90f424a
Create Date: 2026-04-05 13:51:13.902344

This revision was originally autogenerated against a drifted database state that
included unmanaged legacy tables and runtime-created schema objects. It is kept
as a no-op so the migration chain remains linear while later explicit revisions
carry the real schema changes.
"""

from collections.abc import Sequence

revision: str = "01298eb34544"
down_revision: str | None = "a7aca90f424a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""


def downgrade() -> None:
    """Downgrade schema."""
