"""removed aws s3 support

Revision ID: 269b56eec536
Revises: 5b281ae3408c
Create Date: 2026-02-19 04:18:21.986958

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "269b56eec536"
down_revision: str | None = "5b281ae3408c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _drop_table_if_exists(table_name: str) -> None:
    op.execute(sa.text(f'DROP TABLE IF EXISTS "{table_name}" CASCADE'))


def _drop_index_if_exists(index_name: str) -> None:
    op.execute(sa.text(f'DROP INDEX IF EXISTS "{index_name}"'))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_table_if_exists("ar_internal_metadata")
    _drop_table_if_exists("clients")
    _drop_table_if_exists("languages")
    _drop_index_if_exists(op.f("index_submissions_on_token"))
    _drop_table_if_exists("submissions")
    _drop_table_if_exists("schema_migrations")
    _drop_index_if_exists(op.f("idx_activity_details_gin"))
    op.alter_column(
        "activity",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "activity",
        "creation_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "activity",
        "update_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    _drop_index_if_exists(op.f("idx_activity_published"))
    _drop_index_if_exists(op.f("idx_activity_type"))
    _drop_index_if_exists(op.f("idx_block_content_gin"))
    op.alter_column(
        "block",
        "content",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    _drop_index_if_exists(op.f("idx_certifications_config_gin"))
    op.alter_column(
        "certifications",
        "config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "course",
        "creation_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "course",
        "update_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    _drop_index_if_exists(op.f("idx_organization_links_gin"))
    _drop_index_if_exists(op.f("idx_organization_socials_gin"))
    op.alter_column(
        "organization",
        "socials",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "links",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    _drop_index_if_exists(op.f("idx_user_details_gin"))
    _drop_index_if_exists(op.f("idx_user_profile_gin"))
    op.alter_column(
        "user",
        "details",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "profile",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    _drop_index_if_exists(op.f("uq_user_email_lower"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("uq_user_email_lower"),
        "user",
        [sa.literal_column("lower(email::text)")],
        unique=True,
    )
    op.alter_column(
        "user",
        "profile",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "details",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(
        op.f("idx_user_profile_gin"),
        "user",
        ["profile"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_user_details_gin"),
        "user",
        ["details"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "organization",
        "links",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "organization",
        "socials",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(
        op.f("idx_organization_socials_gin"),
        "organization",
        ["socials"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_organization_links_gin"),
        "organization",
        ["links"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "course",
        "update_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "course",
        "creation_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "certifications",
        "config",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(
        op.f("idx_certifications_config_gin"),
        "certifications",
        ["config"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "block",
        "content",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(
        op.f("idx_block_content_gin"),
        "block",
        ["content"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("idx_activity_type"), "activity", ["activity_type"], unique=False
    )
    op.create_index(
        op.f("idx_activity_published"), "activity", ["published"], unique=False
    )
    op.alter_column(
        "activity",
        "update_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "activity",
        "creation_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "activity",
        "details",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(
        op.f("idx_activity_details_gin"),
        "activity",
        ["details"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "schema_migrations",
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("schema_migrations_pkey")),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("language_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stdin", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("expected_output", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("stdout", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "finished_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("memory", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stderr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("number_of_runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cpu_time_limit", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("cpu_extra_time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("wall_time_limit", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("memory_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stack_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "max_processes_and_or_threads",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "enable_per_process_and_thread_time_limit",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "enable_per_process_and_thread_memory_limit",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("max_file_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("compile_output", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("exit_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("exit_signal", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("wall_time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("compiler_options", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "command_line_arguments", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "redirect_stderr_to_stdout",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("callback_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "additional_files", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        sa.Column("enable_network", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("submissions_pkey")),
    )
    op.create_index(
        op.f("index_submissions_on_token"), "submissions", ["token"], unique=False
    )
    op.create_table(
        "languages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("compile_cmd", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("run_cmd", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source_file", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "is_archived",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("languages_pkey")),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("clients_pkey")),
    )
    op.create_table(
        "ar_internal_metadata",
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("ar_internal_metadata_pkey")),
    )
    # ### end Alembic commands ###
