"""fixed missing activity permission metadata

Revision ID: 5447127d3297
Revises: daaf913ae4fc
Create Date: 2026-02-22 07:38:30.338804

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5447127d3297"
down_revision: str | None = "daaf913ae4fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_role_audit_log_actor_id"), table_name="role_audit_log")
    op.drop_index(op.f("ix_role_audit_log_org_timestamp"), table_name="role_audit_log")
    op.drop_index(op.f("ix_role_audit_log_target_role_id"), table_name="role_audit_log")
    op.drop_index(op.f("ix_role_audit_log_timestamp"), table_name="role_audit_log")
    op.drop_table("role_audit_log")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_audit_log",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("actor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("action", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("target_role_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "target_role_slug",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("diff_summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["user.id"],
            name=op.f("role_audit_log_actor_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("role_audit_log_org_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["target_role_id"],
            ["roles.id"],
            name=op.f("role_audit_log_target_role_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("role_audit_log_pkey")),
    )
    op.create_index(
        op.f("ix_role_audit_log_timestamp"),
        "role_audit_log",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_audit_log_target_role_id"),
        "role_audit_log",
        ["target_role_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_audit_log_org_timestamp"),
        "role_audit_log",
        ["org_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_role_audit_log_actor_id"), "role_audit_log", ["actor_id"], unique=False
    )
    # ### end Alembic commands ###
