"""Make trailstep.grade integer

Revision ID: 55b353187efd
Revises: g2b0e16576c4
Create Date: 2025-12-23 13:03:36.619963

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "55b353187efd"
down_revision: str | None = "g2b0e16576c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Allow NULL values temporarily so we can sanitize problematic rows
    op.alter_column(
        "trailstep",
        "grade",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )

    # Sanitize existing values: set blank or non-integer grades to NULL so ALTER ... USING succeeds
    op.execute(
        "UPDATE trailstep SET grade = NULL WHERE trim(COALESCE(grade, '')) = '' OR grade !~ '^[0-9]+$'"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trailstep",
        "grade",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using="grade::integer",
        nullable=True,
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="gradingtypeenum",
        new_values=["NUMERIC", "PERCENTAGE"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="assignment",
                column_name="grading_type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="gradingtypeenum",
        new_values=["ALPHABET", "NUMERIC", "PERCENTAGE"],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="assignment",
                column_name="grading_type",
            )
        ],
        enum_values_to_rename=[],
    )
    op.alter_column(
        "trailstep",
        "grade",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
