"""added coding type activity

Revision ID: 5ac1e82ca152
Revises: 5fc3d9a8b1e2
Create Date: 2026-01-05 20:50:42.471739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "5ac1e82ca152"
down_revision: Union[str, None] = "5fc3d9a8b1e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "PENDING",
        "PROCESSING",
        "COMPLETED",
        "FAILED",
        "PENDING_JUDGE0",
        name="submissionstatus",
    ).create(op.get_bind(), checkfirst=True)
    op.create_table(
        "code_submission",
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("language_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_code", sa.Text(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                "PENDING_JUDGE0",
                name="submissionstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("passed_tests", sa.Integer(), nullable=False),
        sa.Column("total_tests", sa.Integer(), nullable=False),
        sa.Column("execution_time_ms", sa.Float(), nullable=True),
        sa.Column("memory_kb", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "submission_uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("activity_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("org_id", sa.BigInteger(), nullable=True),
        sa.Column("test_results", sa.JSON(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("plagiarism_score", sa.Float(), nullable=True),
        sa.Column("judge0_tokens", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_code_submission_created", "code_submission", ["created_at"], unique=False
    )
    op.create_index(
        "idx_code_submission_score",
        "code_submission",
        ["activity_id", "score"],
        unique=False,
    )
    op.create_index(
        "idx_code_submission_user_activity",
        "code_submission",
        ["user_id", "activity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_code_submission_submission_uuid"),
        "code_submission",
        ["submission_uuid"],
        unique=False,
    )
    op.create_table(
        "hint_usage",
        sa.Column("hint_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("xp_deducted", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("org_id", sa.BigInteger(), nullable=True),
        sa.Column("unlocked_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_hint_usage_user_activity",
        "hint_usage",
        ["user_id", "activity_id"],
        unique=False,
    )
    op.drop_table("ar_internal_metadata")
    op.drop_table("languages")
    op.drop_index(op.f("index_submissions_on_token"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_table("clients")
    op.drop_table("schema_migrations")
    op.sync_enum_values(
        enum_schema="public",
        enum_name="xpsource",
        new_values=[
            "ACTIVITY_COMPLETION",
            "COURSE_COMPLETION",
            "LOGIN_BONUS",
            "QUIZ_COMPLETION",
            "ASSIGNMENT_SUBMISSION",
            "EXAM_COMPLETION",
            "STREAK_BONUS",
            "ADMIN_AWARD",
            "CODE_CHALLENGE_COMPLETION",
            "CODE_CHALLENGE_PERFECT",
            "CODE_CHALLENGE_FIRST_SOLVE",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="xp_transactions",
                column_name="source",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitytypeenum",
        new_values=[
            "TYPE_VIDEO",
            "TYPE_DOCUMENT",
            "TYPE_DYNAMIC",
            "TYPE_ASSIGNMENT",
            "TYPE_EXAM",
            "TYPE_CODE_CHALLENGE",
            "TYPE_CUSTOM",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="activity",
                column_name="activity_type",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitysubtypeenum",
        new_values=[
            "SUBTYPE_DYNAMIC_PAGE",
            "SUBTYPE_VIDEO_YOUTUBE",
            "SUBTYPE_VIDEO_HOSTED",
            "SUBTYPE_DOCUMENT_PDF",
            "SUBTYPE_DOCUMENT_DOC",
            "SUBTYPE_ASSIGNMENT_ANY",
            "SUBTYPE_EXAM_STANDARD",
            "SUBTYPE_CODE_GENERAL",
            "SUBTYPE_CODE_COMPETITIVE",
            "SUBTYPE_CUSTOM",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="activity",
                column_name="activity_sub_type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitysubtypeenum",
        new_values=[
            "SUBTYPE_DYNAMIC_PAGE",
            "SUBTYPE_VIDEO_YOUTUBE",
            "SUBTYPE_VIDEO_HOSTED",
            "SUBTYPE_DOCUMENT_PDF",
            "SUBTYPE_DOCUMENT_DOC",
            "SUBTYPE_ASSIGNMENT_ANY",
            "SUBTYPE_EXAM_STANDARD",
            "SUBTYPE_CUSTOM",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="activity",
                column_name="activity_sub_type",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitytypeenum",
        new_values=[
            "TYPE_VIDEO",
            "TYPE_DOCUMENT",
            "TYPE_DYNAMIC",
            "TYPE_ASSIGNMENT",
            "TYPE_EXAM",
            "TYPE_CUSTOM",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="activity",
                column_name="activity_type",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="xpsource",
        new_values=[
            "ACTIVITY_COMPLETION",
            "COURSE_COMPLETION",
            "LOGIN_BONUS",
            "QUIZ_COMPLETION",
            "ASSIGNMENT_SUBMISSION",
            "EXAM_COMPLETION",
            "STREAK_BONUS",
            "ADMIN_AWARD",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="xp_transactions",
                column_name="source",
            )
        ],
        enum_values_to_rename=[],
    )
    op.create_table(
        "schema_migrations",
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("schema_migrations_pkey")),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("clients_pkey")),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("language_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stdin", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("expected_output", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("stdout", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "finished_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("memory", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stderr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("number_of_runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cpu_time_limit", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("cpu_extra_time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("wall_time_limit", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("memory_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stack_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "max_processes_and_or_threads",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "enable_per_process_and_thread_time_limit",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "enable_per_process_and_thread_memory_limit",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("max_file_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("compile_output", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("exit_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("exit_signal", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("wall_time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("compiler_options", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "command_line_arguments", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "redirect_stderr_to_stdout",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("callback_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "additional_files", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        sa.Column("enable_network", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("submissions_pkey")),
    )
    op.create_index(
        op.f("index_submissions_on_token"), "submissions", ["token"], unique=False
    )
    op.create_table(
        "languages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("compile_cmd", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("run_cmd", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source_file", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "is_archived",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("languages_pkey")),
    )
    op.create_table(
        "ar_internal_metadata",
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("ar_internal_metadata_pkey")),
    )
    op.drop_index("idx_hint_usage_user_activity", table_name="hint_usage")
    op.drop_table("hint_usage")
    op.drop_index(
        op.f("ix_code_submission_submission_uuid"), table_name="code_submission"
    )
    op.drop_index("idx_code_submission_user_activity", table_name="code_submission")
    op.drop_index("idx_code_submission_score", table_name="code_submission")
    op.drop_index("idx_code_submission_created", table_name="code_submission")
    op.drop_table("code_submission")
    sa.Enum(
        "PENDING",
        "PROCESSING",
        "COMPLETED",
        "FAILED",
        "PENDING_JUDGE0",
        name="submissionstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
