"""add_course_discussions_tables

Revision ID: a7f3a5b6beac
Revises: 9e031a0358d1
Create Date: 2025-07-29 16:55:34.574059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f3a5b6beac'
down_revision: Union[str, None] = '9e031a0358d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursediscussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discussion_uuid', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('POST', 'REPLY', name='discussiontype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'HIDDEN', 'DELETED', name='discussionstatusenum'), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_discussion_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('replies_count', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.String(), nullable=False),
    sa.Column('update_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_discussion_id'], ['coursediscussion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussionlike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['coursediscussion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussionlike')
    op.drop_table('coursediscussion')
    # ### end Alembic commands ###
