"""remove email verification

Revision ID: b84feb892d7a
Revises: d4e5f6a7b8c9
Create Date: 2026-04-11 17:18:34.949653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b84feb892d7a"
down_revision: Union[str, None] = "d4e5f6a7b8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS "organization"')
    op.drop_index(
        op.f("document_chunks_collection_name_idx"),
        table_name="document_chunks",
        if_exists=True,
    )
    op.drop_index(
        op.f("document_chunks_embedding_hnsw_idx"),
        table_name="document_chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
        if_exists=True,
    )
    op.drop_index(
        op.f("document_chunks_inserted_at_idx"),
        table_name="document_chunks",
        if_exists=True,
    )
    op.execute("DROP TABLE IF EXISTS document_chunks")
    op.alter_column(
        "auth_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_auth_sessions_refresh_token_hash"),
        "auth_sessions",
        ["refresh_token_hash"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_auth_sessions_session_id"),
        "auth_sessions",
        ["session_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_auth_sessions_token_family_id"),
        "auth_sessions",
        ["token_family_id"],
        unique=False,
        if_not_exists=True,
    )
    op.execute('ALTER TABLE "user" DROP COLUMN IF EXISTS email_verified_at')
    op.execute('ALTER TABLE "user" DROP COLUMN IF EXISTS email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("email_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user",
        sa.Column(
            "email_verified_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_auth_sessions_token_family_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_session_id"), table_name="auth_sessions")
    op.drop_index(
        op.f("ix_auth_sessions_refresh_token_hash"), table_name="auth_sessions"
    )
    op.alter_column(
        "auth_sessions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_table(
        "document_chunks",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("collection_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("document", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "inserted_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("document_chunks_pkey")),
    )
    op.create_index(
        op.f("document_chunks_inserted_at_idx"),
        "document_chunks",
        ["inserted_at"],
        unique=False,
    )
    op.create_index(
        op.f("document_chunks_embedding_hnsw_idx"),
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("document_chunks_collection_name_idx"),
        "document_chunks",
        ["collection_name"],
        unique=False,
    )
    op.create_table(
        "organization",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("about", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "socials",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "links",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("logo_image", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("thumbnail_image", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "previews",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("label", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("slug", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("org_uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("creation_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("update_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "landing",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("creator_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
            name=op.f("organization_creator_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("organization_pkey")),
    )
    # ### end Alembic commands ###
