"""sync backend models with db schema

Revision ID: c6ac02f61616
Revises: b32f34573336
Create Date: 2026-02-08 13:24:32.665067

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c6ac02f61616"
down_revision: str | None = "b32f34573336"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP INDEX IF EXISTS idx_user_perms_lookup"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_user_perms_permission"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_user_perms_role"))
    op.execute(sa.text("DROP TABLE IF EXISTS user_permissions"))
    op.execute(sa.text("DROP TABLE IF EXISTS clients"))
    op.execute(sa.text("DROP TABLE IF EXISTS role_permissions_backup"))
    op.execute(sa.text("DROP INDEX IF EXISTS idx_resource_permissions_type_id"))
    op.execute(sa.text("DROP INDEX IF EXISTS ix_resource_permissions_user_resource"))
    op.execute(sa.text("DROP TABLE IF EXISTS resource_permissions"))
    op.execute(sa.text("DROP TABLE IF EXISTS ar_internal_metadata"))
    op.execute(sa.text("DROP TABLE IF EXISTS userorganization_backup"))
    op.execute(sa.text("DROP TABLE IF EXISTS schema_migrations"))
    op.execute(sa.text("DROP TABLE IF EXISTS languages"))
    op.execute(sa.text("DROP INDEX IF EXISTS index_submissions_on_token"))
    op.execute(sa.text("DROP TABLE IF EXISTS submissions"))
    op.execute(sa.text("DROP TABLE IF EXISTS install"))
    op.execute(
        sa.text(
            "ALTER TABLE IF EXISTS userorganization "
            "DROP CONSTRAINT IF EXISTS userorganization_role_id_fkey"
        )
    )
    op.execute(sa.text("DROP TABLE IF EXISTS role"))
    op.execute(sa.text("DROP TABLE IF EXISTS user_roles_backup"))
    op.alter_column(
        "permissions",
        "description",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "permissions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.execute(sa.text("DROP INDEX IF EXISTS ix_permissions_action_resource_scope"))
    op.execute(
        sa.text("ALTER TABLE permissions DROP CONSTRAINT IF EXISTS uq_permissions_name")
    )
    op.drop_table_comment(
        "permissions",
        existing_comment="Permission definitions (e.g., course:update:own)",
        schema=None,
    )
    op.execute(sa.text("ALTER TABLE permissions DROP COLUMN IF EXISTS is_dangerous"))
    op.alter_column(
        "roles",
        "description",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.alter_column(
        "roles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_table_comment(
        "roles",
        existing_comment="Role definitions (e.g., instructor, admin)",
        schema=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "roles",
        "Role definitions (e.g., instructor, admin)",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "roles",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roles",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "roles",
        "description",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.add_column(
        "permissions",
        sa.Column(
            "is_dangerous",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table_comment(
        "permissions",
        "Permission definitions (e.g., course:update:own)",
        existing_comment=None,
        schema=None,
    )
    op.create_unique_constraint(
        op.f("uq_permissions_name"),
        "permissions",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_permissions_action_resource_scope"),
        "permissions",
        ["action", "resource_type", "scope"],
        unique=False,
    )
    op.alter_column(
        "permissions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "permissions",
        "description",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.create_table(
        "user_roles_backup",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "granted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("granted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "role",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "role_type",
            postgresql.ENUM(
                "TYPE_ORGANIZATION",
                "TYPE_ORGANIZATION_API_TOKEN",
                "TYPE_GLOBAL",
                name="roletypeenum",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("role_uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("creation_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("update_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("role_org_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("role_pkey")),
    )
    op.create_table(
        "install",
        sa.Column("step", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("install_uuid", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("creation_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("update_date", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("install_pkey")),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("language_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stdin", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("expected_output", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("stdout", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("status_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "finished_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("memory", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stderr", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("number_of_runs", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("cpu_time_limit", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("cpu_extra_time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("wall_time_limit", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("memory_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("stack_limit", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "max_processes_and_or_threads",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "enable_per_process_and_thread_time_limit",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "enable_per_process_and_thread_memory_limit",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("max_file_size", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("compile_output", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("exit_code", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("exit_signal", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("wall_time", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("compiler_options", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "command_line_arguments", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "redirect_stderr_to_stdout",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("callback_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "additional_files", postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
        sa.Column("enable_network", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("submissions_pkey")),
    )
    op.create_index(
        op.f("index_submissions_on_token"), "submissions", ["token"], unique=False
    )
    op.create_table(
        "languages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("compile_cmd", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("run_cmd", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source_file", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "is_archived",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("languages_pkey")),
    )
    op.create_table(
        "schema_migrations",
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version", name=op.f("schema_migrations_pkey")),
    )
    op.create_table(
        "userorganization_backup",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("creation_date", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("update_date", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "ar_internal_metadata",
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("value", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("ar_internal_metadata_pkey")),
    )
    op.create_table(
        "resource_permissions",
        sa.Column("resource_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "resource_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "granted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("granted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["user.id"],
            name=op.f("resource_permissions_granted_by_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("resource_permissions_permission_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("resource_permissions_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("resource_permissions_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "resource_type",
            "resource_id",
            "permission_id",
            name=op.f("uq_resource_permission"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_resource_permissions_user_resource"),
        "resource_permissions",
        ["user_id", "resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_resource_permissions_type_id"),
        "resource_permissions",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_table(
        "role_permissions_backup",
        sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "granted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("granted_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("grant_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "clients",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("clients_pkey")),
    )
    op.create_table(
        "user_permissions",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("permission_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("org_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("scope", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "granted_via_role_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Role that granted this permission (NULL for direct assignments) - preserves audit trail",
        ),
        sa.Column(
            "granted_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["granted_via_role_id"],
            ["roles.id"],
            name=op.f("fk_user_permissions_role_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organization.id"],
            name=op.f("fk_user_permissions_org_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_user_permissions_permission_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_permissions_user_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "permission_id", "org_id", name=op.f("user_permissions_pkey")
        ),
        comment="Flattened user permissions (denormalized from user_roles + role_permissions for performance)",
    )
    op.create_index(
        op.f("idx_user_perms_role"),
        "user_permissions",
        ["granted_via_role_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_user_perms_permission"),
        "user_permissions",
        ["permission_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_user_perms_lookup"),
        "user_permissions",
        ["user_id", "org_id"],
        unique=False,
    )
    # ### end Alembic commands ###
