"""add_exam_tables

Revision ID: cf0a7109b89b
Revises: 22bba238d2fa
Create Date: 2025-12-26 20:02:25.072678

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "cf0a7109b89b"
down_revision: str | None = "22bba238d2fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitytypeenum",
        new_values=[
            "TYPE_VIDEO",
            "TYPE_DOCUMENT",
            "TYPE_DYNAMIC",
            "TYPE_ASSIGNMENT",
            "TYPE_EXAM",
            "TYPE_CUSTOM",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="activity",
                column_name="activity_type",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitysubtypeenum",
        new_values=[
            "SUBTYPE_DYNAMIC_PAGE",
            "SUBTYPE_VIDEO_YOUTUBE",
            "SUBTYPE_VIDEO_HOSTED",
            "SUBTYPE_DOCUMENT_PDF",
            "SUBTYPE_DOCUMENT_DOC",
            "SUBTYPE_ASSIGNMENT_ANY",
            "SUBTYPE_EXAM_STANDARD",
            "SUBTYPE_CUSTOM",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="activity",
                column_name="activity_sub_type",
            )
        ],
        enum_values_to_rename=[],
    )

    # Create exam table
    op.create_table(
        "exam",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exam_uuid", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("creation_date", sa.String(), nullable=False),
        sa.Column("update_date", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["activity.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["chapter_id"], ["chapter.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["course_id"], ["course.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_exam_exam_uuid", "exam", ["exam_uuid"], unique=True)

    # Create question table
    op.create_table(
        "question",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_uuid", sa.String(), nullable=False),
        sa.Column("question_text", sa.String(), nullable=False),
        sa.Column("question_type", sa.String(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.String(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("answer_options", sa.JSON(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("creation_date", sa.String(), nullable=False),
        sa.Column("update_date", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["exam_id"], ["exam.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_question_question_uuid", "question", ["question_uuid"], unique=True
    )

    # Create examattempt table
    op.create_table(
        "examattempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_uuid", sa.String(), nullable=False),
        sa.Column("exam_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("max_score", sa.Integer(), nullable=True),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("question_order", sa.JSON(), nullable=False),
        sa.Column("violations", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=True),
        sa.Column("submitted_at", sa.String(), nullable=True),
        sa.Column("creation_date", sa.String(), nullable=False),
        sa.Column("update_date", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["exam_id"], ["exam.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organization.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_examattempt_attempt_uuid", "examattempt", ["attempt_uuid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop exam tables
    op.drop_index("ix_examattempt_attempt_uuid", table_name="examattempt")
    op.drop_table("examattempt")
    op.drop_index("ix_question_question_uuid", table_name="question")
    op.drop_table("question")
    op.drop_index("ix_exam_exam_uuid", table_name="exam")
    op.drop_table("exam")

    # Revert enum changes
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitysubtypeenum",
        new_values=[
            "SUBTYPE_DYNAMIC_PAGE",
            "SUBTYPE_VIDEO_YOUTUBE",
            "SUBTYPE_VIDEO_HOSTED",
            "SUBTYPE_DOCUMENT_PDF",
            "SUBTYPE_DOCUMENT_DOC",
            "SUBTYPE_ASSIGNMENT_ANY",
            "SUBTYPE_CUSTOM",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="activity",
                column_name="activity_sub_type",
            )
        ],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="activitytypeenum",
        new_values=[
            "TYPE_VIDEO",
            "TYPE_DOCUMENT",
            "TYPE_DYNAMIC",
            "TYPE_ASSIGNMENT",
            "TYPE_CUSTOM",
        ],
        affected_columns=[
            TableReference(
                table_schema="public",
                table_name="activity",
                column_name="activity_type",
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
