"""add_user_theme_and_locale

Revision ID: f1a9aefaf3ac
Revises: 9e031a0358d1
Create Date: 2025-10-01 22:44:37.730698

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1a9aefaf3ac"
down_revision: Union[str, None] = "9e031a0358d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("theme", sa.String(), nullable=True))
    op.add_column("user", sa.Column("locale", sa.String(), nullable=True))

    # Set default values for existing users
    op.execute("UPDATE \"user\" SET theme = 'default' WHERE theme IS NULL")
    op.execute("UPDATE \"user\" SET locale = 'ru-RU' WHERE locale IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "locale")
    op.drop_column("user", "theme")
    # ### end Alembic commands ###
