#!/usr/bin/env python3
"""
Permission Schema Code Generator

Generates Python enums and TypeScript types from the shared permissions.yaml schema.
This ensures frontend and backend use the exact same permission definitions.

Usage:
    python scripts/generate_permissions.py
"""

import yaml
from pathlib import Path
from typing import Any
from datetime import datetime


def load_schema(schema_path: Path) -> dict[str, Any]:
    """Load the YAML permission schema."""
    with open(schema_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)


def generate_python_enums(schema: dict[str, Any], output_path: Path) -> None:
    """Generate Python enums from schema."""

    actions = schema['actions']
    scopes = schema['scopes']
    resources = schema['resources']

    python_code = f'''"""
Generated Permission Enums

Auto-generated from shared/permissions.yaml
DO NOT EDIT THIS FILE MANUALLY
Generated: {datetime.now().isoformat()}
"""

from enum import Enum


class Action(str, Enum):
    """Actions that can be performed on resources."""

'''

    for action in actions:
        action_upper = action.upper()
        python_code += f'    {action_upper} = "{action}"\n'

    python_code += '\n\nclass ResourceType(str, Enum):\n'
    python_code += '    """Types of resources in the system."""\n    \n'

    for resource in resources:
        resource_upper = resource.upper()
        python_code += f'    {resource_upper} = "{resource}"\n'

    python_code += '\n\nclass Scope(str, Enum):\n'
    python_code += '    """Scope of a permission - determines what resources it applies to."""\n    \n'

    for scope in scopes:
        scope_upper = scope.upper()
        python_code += f'    {scope_upper} = "{scope}"\n'

    python_code += '\n\ndef build_permission_name(\n'
    python_code += '    resource: ResourceType,\n'
    python_code += '    action: Action,\n'
    python_code += '    scope: Scope = Scope.ALL,\n'
    python_code += ') -> str:\n'
    python_code += '    """Build a permission name from components."""\n'
    python_code += '    return f"{resource.value}:{action.value}:{scope.value}"\n'

    python_code += '\n\ndef parse_permission_name(name: str) -> tuple[str, str, str]:\n'
    python_code += '    """Parse a permission name into components."""\n'
    python_code += '    parts = name.split(":")\n'
    python_code += '    if len(parts) != 3:\n'
    python_code += '        raise ValueError(f"Invalid permission name: {name}")\n'
    python_code += '    return parts[0], parts[1], parts[2]\n'

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(python_code)

    print(f"✅ Generated Python enums: {output_path}")


def generate_typescript_types(schema: dict[str, Any], output_path: Path) -> None:
    """Generate TypeScript types from schema."""

    actions = schema['actions']
    scopes = schema['scopes']
    resources = schema['resources']
    roles = schema['roles']

    ts_code = f'''/**
 * Generated Permission Types
 *
 * Auto-generated from shared/permissions.yaml
 * DO NOT EDIT THIS FILE MANUALLY
 * Generated: {datetime.now().isoformat()}
 */

// Actions that can be performed on resources
export const Actions = {{
'''

    for action in actions:
        action_upper = action.upper()
        ts_code += f"  {action_upper}: '{action}',\n"

    ts_code += '} as const;\n\n'
    ts_code += 'export type Action = (typeof Actions)[keyof typeof Actions];\n\n'

    ts_code += '// Types of resources in the system\n'
    ts_code += 'export const ResourceTypes = {\n'

    for resource in resources:
        resource_upper = resource.upper()
        ts_code += f"  {resource_upper}: '{resource}',\n"

    ts_code += '} as const;\n\n'
    ts_code += 'export type ResourceType = (typeof ResourceTypes)[keyof typeof ResourceTypes];\n\n'

    ts_code += '// Scopes define the extent of a permission\n'
    ts_code += 'export const Scopes = {\n'

    for scope in scopes:
        scope_upper = scope.upper()
        ts_code += f"  {scope_upper}: '{scope}',\n"

    ts_code += '} as const;\n\n'
    ts_code += 'export type Scope = (typeof Scopes)[keyof typeof Scopes];\n\n'

    ts_code += '// Role slugs\n'
    ts_code += 'export const RoleSlugs = {\n'

    for role_slug in roles.keys():
        role_const = role_slug.upper().replace('-', '_')
        ts_code += f"  {role_const}: '{role_slug}',\n"

    ts_code += '} as const;\n\n'
    ts_code += 'export type RoleSlug = (typeof RoleSlugs)[keyof typeof RoleSlugs];\n\n'

    ts_code += '''/**
 * Build a permission name from components.
 * Format: {resource}:{action}:{scope}
 * Example: course:update:own
 */
export function buildPermissionName(
  resource: ResourceType,
  action: Action,
  scope: Scope = Scopes.ALL,
): string {
  return `${resource}:${action}:${scope}`;
}

/**
 * Parse a permission name into components.
 */
export function parsePermissionName(name: string): {
  resource: ResourceType;
  action: Action;
  scope: Scope;
} | null {
  const parts = name.split(':');
  if (parts.length !== 3) {
    return null;
  }
  return {
    resource: parts[0] as ResourceType,
    action: parts[1] as Action,
    scope: parts[2] as Scope,
  };
}

/**
 * Check if a role slug is an admin role.
 */
export function isAdminRole(roleSlug: string): boolean {
  return (
    roleSlug === RoleSlugs.SUPER_ADMIN ||
    roleSlug === RoleSlugs.ORG_ADMIN
  );
}

/**
 * Check if a role slug is instructor or higher.
 */
export function isInstructorOrHigher(roleSlug: string): boolean {
  return (
    roleSlug === RoleSlugs.SUPER_ADMIN ||
    roleSlug === RoleSlugs.ORG_ADMIN ||
    roleSlug === RoleSlugs.MAINTAINER ||
    roleSlug === RoleSlugs.INSTRUCTOR
  );
}

/**
 * Permission name type for better type safety.
 */
export type PermissionName = `${ResourceType}:${Action}:${Scope}`;

/**
 * Permission check result.
 */
export interface PermissionCheck {
  action: Action;
  resource: ResourceType;
  scope?: Scope;
}
'''

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(ts_code)

    print(f"✅ Generated TypeScript types: {output_path}")


def generate_role_permissions(schema: dict[str, Any], output_path: Path) -> None:
    """Generate Python dict mapping roles to permissions."""

    roles = schema['roles']

    python_code = f'''"""
Generated Role Permission Mappings

Auto-generated from shared/permissions.yaml
DO NOT EDIT THIS FILE MANUALLY
Generated: {datetime.now().isoformat()}
"""

from src.db.permissions.generated_enums import Action, ResourceType, Scope

# Role slug constants
class RoleSlug:
    """Standard role slugs used across the platform."""

'''

    for role_slug in roles.keys():
        role_const = role_slug.upper().replace('-', '_')
        python_code += f'    {role_const} = "{role_slug}"\n'

    python_code += '\n\n# Role permission mappings\n'
    python_code += 'ROLE_PERMISSIONS: dict[str, list[str]] = {\n'

    for role_slug, role_data in roles.items():
        python_code += f'    "{role_slug}": [\n'
        for perm in role_data['permissions']:
            python_code += f'        "{perm}",\n'
        python_code += '    ],\n'

    python_code += '}\n\n'

    python_code += '''# Role groups for common permission checks
ADMIN_ROLE_SLUGS = frozenset({
    RoleSlug.SUPER_ADMIN,
    RoleSlug.ORG_ADMIN,
})

ADMIN_OR_MAINTAINER_SLUGS = frozenset({
    RoleSlug.SUPER_ADMIN,
    RoleSlug.ORG_ADMIN,
    RoleSlug.MAINTAINER,
})

INSTRUCTOR_OR_HIGHER_SLUGS = frozenset({
    RoleSlug.SUPER_ADMIN,
    RoleSlug.ORG_ADMIN,
    RoleSlug.MAINTAINER,
    RoleSlug.INSTRUCTOR,
})

CONTENT_CREATOR_SLUGS = frozenset({
    RoleSlug.SUPER_ADMIN,
    RoleSlug.ORG_ADMIN,
    RoleSlug.MAINTAINER,
    RoleSlug.INSTRUCTOR,
})


def is_admin_role(role_slug: str) -> bool:
    """Check if the role slug is an admin role."""
    return role_slug in ADMIN_ROLE_SLUGS


def is_admin_or_maintainer_role(role_slug: str) -> bool:
    """Check if the role slug is admin or maintainer."""
    return role_slug in ADMIN_OR_MAINTAINER_SLUGS


def is_instructor_or_higher_role(role_slug: str) -> bool:
    """Check if the role slug is instructor or higher privilege."""
    return role_slug in INSTRUCTOR_OR_HIGHER_SLUGS


def is_content_creator_role(role_slug: str) -> bool:
    """Check if the role slug can create content."""
    return role_slug in CONTENT_CREATOR_SLUGS
'''

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(python_code)

    print(f"✅ Generated role mappings: {output_path}")


def main():
    """Main entry point."""
    root_dir = Path(__file__).parent.parent
    schema_path = root_dir / "shared" / "permissions.yaml"

    print(f"📖 Loading schema from: {schema_path}")
    schema = load_schema(schema_path)

    # Generate Python enums
    python_output = root_dir / "apps" / "api" / "src" / "db" / "permissions" / "generated_enums.py"
    generate_python_enums(schema, python_output)

    # Generate TypeScript types
    ts_output = root_dir / "apps" / "web" / "types" / "generated_permissions.ts"
    generate_typescript_types(schema, ts_output)

    # Generate role permission mappings
    role_output = root_dir / "apps" / "api" / "src" / "db" / "permissions" / "generated_roles.py"
    generate_role_permissions(schema, role_output)

    print("\n✅ All code generation complete!")
    print("\nNext steps:")
    print("1. Update imports to use generated enums instead of manual definitions")
    print("2. Run tests to ensure generated code works correctly")
    print("3. Remove old manual permission definitions")


if __name__ == "__main__":
    main()
