[project]
description = "OpenU Backend"
name = "openu-api"
version = "0.1.0"
requires-python = ">=3.13.4"
dependencies = [
  "boto3>=1.40.37",
  "botocore>=1.40.37",
  "fastapi[standard-no-fastapi-cloud-cli]==0.117.1",
  "fastapi-another-jwt-auth>=0.1.11",
  "langchain>=0.3.27",
  "langchain-chroma>=0.2.6",
  "langchain-community>=0.3.29",
  "langchain-core>=0.3.76",
  "langchain-openai>=0.3.33",
  "langchain-text-splitters>=0.3.11",
  "openai>=1.109.1",
  "psycopg[binary,pool]>=3.2.10",
  "pydantic[email]>=2.11.9",
  "python-dotenv>=1.1.1",
  "pyyaml>=6.0.2",
  "redis[hiredis]>=6.4.0",
  "resend>=2.14.0",
  "sqlmodel>=0.0.25",
  "tiktoken>=0.11.0",
  "typer>=0.19.2",
  "chromadb>=1.1.0",
  "alembic>=1.16.5",
  "alembic-postgresql-enum>=1.8.0",
  "stripe>=12.5.1",
  "logfire[fastapi,sqlalchemy]>=4.9.0",
  "beautifulsoup4>=4.13.5",
  "python-ulid>=3.1.0",
  "argon2-cffi>=25.1.0",
  "orjson>=3.11.3",
  "httptools>=0.6.4",
  "brotli>=1.1.0",
  "cachetools>=6.2.0",
  "python-jose>=3.5.0",
]

[dependency-groups]

dev = [
  "faker>=37.8.0",
  "pyflakes>=3.4.0",
  "pytest>=8.4.2",
  "pytest-asyncio>=1.2.0",
  "pytest-cov<6.0.0",
  "ruff>=0.13.1",
]


[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
markers = ["asyncio: mark test as async"]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::UserWarning",
  "ignore:.*crypt.*deprecated.*",
  "ignore:.*utcnow.*deprecated.*",
  "ignore:.*obj.dict.*deprecated.*",
  "ignore:.*Instrumentation will have no effect.*",
  "ignore:.*handler names should be lower-case.*",
  "ignore:.*Importing tools from langchain is deprecated.*",
]

[tool.ruff]
target-version = "py314"
# lint.select = ["ALL"]
lint.fixable = ["ALL"]
lint.ignore = [
  "F401",
  "COM812",  # missing trailing comma (stylistic, optional)
  "DTZ005",  # datetime.now() used without tzinfo (not always relevant)
  "T20",     # flake8-print (allow print statements for debugging/logging)
  "TC002",   # type checking import block placement
  "TC001",   # type checking import not at top of file
  "TC003",   # type checking import formatting
  "PLR2004", # magic value used in comparison (often acceptable)
  "D",       # all docstring-related rules disabled
  "D100",    # missing docstring in public module
  "S101",    # Use of `assert` detected
  "TD002",   # Missing author in TODO;
]

format.quote-style = "double"

[tool.logfire]
ignore_no_config = true
