[project]
description = "OpenU Backend"
name = "openu-api"
version = "0.1.0"
requires-python = ">=3.13.2"
dependencies = [
  "boto3>=1.38.46",
  "botocore>=1.38.46",
  "faker>=37.4.0",
  "fastapi==0.115.14",
  "fastapi-another-jwt-auth>=0.1.11",
  "httpx>=0.28.1",
  "langchain>=0.3.26",
  "langchain-chroma>=0.2.4",
  "langchain-community>=0.3.26",
  "langchain-core>=0.3.66",
  "langchain-openai>=0.3.27",
  "langchain-text-splitters>=0.3.8",
  "openai>=1.93.0",
  "psycopg2-binary>=2.9.10",
  "pydantic[email]>=2.11.7",
  "pytest>=8.4.1",
  "python-dotenv>=1.1.1",
  "python-multipart>=0.0.20",
  "pyyaml>=6.0.2",
  "redis[hiredis]>=6.2.0",
  "resend>=2.10.0",
  "sqlmodel>=0.0.24",
  "tiktoken>=0.9.0",
  "uvicorn>=0.35.0",
  "typer>=0.16.0",
  "chromadb>=1.0.13",
  "alembic>=1.16.2",
  "alembic-postgresql-enum>=1.7.0",
  "sqlalchemy-utils>=0.41.2",
  "stripe>=12.2.0",
  "logfire[sqlalchemy]>=3.21.1",
  "beautifulsoup4>=4.13.4",
  "opentelemetry-instrumentation-fastapi>=0.55b1",
  "python-ulid>=3.0.0",
  "argon2-cffi>=25.1.0",
]

[tool.ruff]
target-version = "py313"
lint.ignore = ["E501", "E712"]

format.quote-style = "double"

[tool.logfire]
ignore_no_config = true

[dependency-groups]
dev = ["ruff>=0.11.12"]
